# Tensor flow basics fundas

In [ ]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
print(tf.__version__)

1.3.0


In [4]:
# word tensor is basically a fancy word for n-dimensional array

In [5]:
hello = tf.constant('Hello')
world = tf.constant('World')

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


### Note above direct printing does not work good for tensor, the reason being is that the definition of all the variables or placeholders are just a structure creation, to run the anything on tensor we need to run it inside the session

In [18]:
with tf.Session() as sess:
    result = sess.run(hello + " " + world)

In [19]:
result

b'Hello World'

In [20]:
print(result)

b'Hello World'


In [12]:
a = tf.constant(10)
b = tf.constant(20)

res = tf.add(a,b) # note we can use both add as well as + sign. tensorflow is smart enough to understand the difference
res1 = a + b

In [13]:
print(res,res1)

Tensor("Add:0", shape=(), dtype=int32) Tensor("add_1:0", shape=(), dtype=int32)


In [21]:
# above it displayed the object information rather than the actual result, to get back the exact result, we need to 
# run the above operation inside a tensorflow session

with tf.Session() as sess:
    fin_res = sess.run(res1) # note the two way to evaluate the tensorflow operation
    fin_res1 = res1.eval() # 1. through sess.run 2. eval (method)

In [22]:
fin_res

30

In [23]:
fin_res1

30

In [24]:
fill_mat = tf.fill((4,4),10)

In [25]:
myzeros = tf.zeros((4,4))

In [26]:
myones = tf.ones((4,4))

In [27]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [28]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

### note nothing has been executed because of the same reason discussed before.

In [29]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [30]:
my_ops = [fill_mat,myones,myzeros,myrandn,myrandu]

### use of interactive session, to replace the use of with tf.Session(). Really usefull for notebook purpose. On interactive sesion rest of the cell will be pretended as if with session has been called before.

In [31]:
# how to use interactive session

sess = tf.InteractiveSession()

In [33]:
for op in my_ops:
    print(op.eval())
    print("\n")

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.73702729 -0.89834166  0.29161274  0.94359463]
 [ 0.92679614 -0.96225691 -0.47855073  1.04167473]
 [ 1.75164735 -0.76927137  0.01451476 -3.0244894 ]
 [-2.6852684   0.1105025   1.5629071   2.4379921 ]]


[[ 0.75381637  0.01775157  0.28644943  0.04152858]
 [ 0.81025338  0.03645122  0.79656684  0.81280351]
 [ 0.39344466  0.17828417  0.31445193  0.77543521]
 [ 0.05552089  0.4570719   0.2040292   0.49674964]]




In [34]:
a = tf.constant([[1,2],[3,4]])

In [35]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [38]:
b = tf.constant([[10],[100]])

In [39]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [40]:
result = tf.matmul(a,b)

In [42]:
sess.run(result)   ## Session.run can be used to 

array([[210],
       [430]])

In [43]:
result.eval()

array([[210],
       [430]])

## In tensorflow each node is an operation with possible inputs that can supply some output